version: 2
jobs:
  build:
    docker:
      - image: mmanogaran/ciftify_ci:0.1
    steps:
      - checkout:
          path: /home/ciftify
      - run:
          name: Set Paths
          command: |
            echo 'export PATH=/homeciftify/ciftify/bin:$PATH' >> $BASH_ENV
            echo 'export PYTHONPATH=/home/ciftify/:$PYTHONPATH' >> $BASH_ENV
            echo 'export CIFTIFY_TEMPLATES=/home/ciftify/data' >> $BASH_ENV
            printenv
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /home/ciftify

  dependencies:
    docker:
      - image: mmanogaran/ciftify_ci:0.1
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "/home/ciftify/cifti_requirements.txt" }}
            - deps1
      - run:
          name: install dependencies
          command: |
            python3 -m venv /home/venv
            source /home/venv/bin/activate
            pip install -r /home/ciftify/cifti_requirements.txt
      - save_cache:
          paths:
            - "/home/venv"
          key:  deps1-{{ .Branch }}-{{ checksum "/home/ciftify/cifti_requirements.txt" }}

  pytest:
    docker:
      - image: mmanogaran/ciftify_ci:0.1
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "/home/ciftify/cifti_requirements.txt" }}
      - run:
          name: run tests
          command: |
            source  /home/venv/bin/activate
            mkdir -p /home/outputs/pytest/
            cd /home/ciftify
            pytest --junitxml=/home/outputs/pytest/results.xml tests/*py
      - store_artifacts:
          path: /home/outputs/pytest
          destination: pytest
      - store_test_results:
          path: /home/outputs

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - dependencies:
          requires:
            - build
      - pytest:
          requires:
            - dependencies
